### ISSUE TITLE
Documentation -- Fichier des codes commutateurs

### ISSUE THREAD

**Issue by linquant** [maditnerd/genericRadio#1]
Bonjour,

Sur l'une des premières versions, il y avait un document excel avec la liste des codes en fonction des commutateurs des prises.

Est il possible d'avoir ce fichier, je ne le trouve pas ???

Très bon boulot.
Merci

**Comment by linquant** [comment]
Re:

Voila le lien pour ce qui cherche.
https://drive.google.com/folderview?id=0B_mF8V7Pb_5Dbkx5WXdlQ2E1OE0&usp=sharing

C'est pratique quand on a pas de récepteurs pour scanner.

**Comment by remisarrailh** [comment]
http://maditnerd.github.io/genericRadio/
